export const ENTER_USER_PASSWORD = 'ENTER_USER_PASSWORD';

export const IS_LOGGED_IN = 'IS_LOGGED_IN';

export const ENTER_NEW_ARTICLE = 'ENTER_NEW_ARTICLE';

export const SUBMIT_NEW_ARTICLE = 'SUBMIT_NEW_ARTICLE';

export const POPULATE_MENUS = 'POPULATE_MENUS';
